### ISSUE TITLE
How to use GLSL 100 shaders?

### ISSUE THREAD

**Issue by janEntikan** [treeform/boxy#38]
I see there is GLSL 100 but I'm not sure how to use it (without using emcripten). I am too poor to have access to GLSL 410 (I have 130).

**Comment by treeform** [comment]
Sorry, In the current boxy GLSL 100 is not supported even emcripten is currently broken.

We would need to back-port the GLSL 410 functionality, its not as simple as changing the version. 

The `GLSL #version 110` came out 2004 I don't want to support 18 year old hardware at this time.

You can try reverting to back before the big shader changes and try editing the source to get emcripten's shades to work again. But you are on your own sorry!

**Comment by janEntikan** [comment]
I also have a 150 machine. I'll see what I can do with an older commit. Do note that GLSL 410 is quite a tall order hardware-wise, especially with the current state of the GPU world.
