### ISSUE TITLE
Unable to run basic_windy on X11 Linux

### ISSUE THREAD

**Issue by ajusa** [treeform/boxy#44]
Hello,

I'm currently trying to just use this library on my machine. My code is

```nim
import boxy, opengl, windy

let window = newWindow("Windy + Boxy", ivec2(1280, 800))
makeContextCurrent(window)

loadExtensions()

let bxy = newBoxy()

# Load the images.
bxy.addImage("bg", readImage("./uncle.png"))

var frame: int

# Called when it is time to draw a new frame.
window.onFrame = proc() =
  # Clear the screen and begin a new frame.
  bxy.beginFrame(window.size)
  # Draw the bg.
  bxy.drawImage("bg", rect = rect(vec2(0, 0), window.size.vec2))
  # End this frame, flushing the draw commands.
  bxy.endFrame()
  # Swap buffers displaying the new Boxy frame.
  window.swapBuffers()
  inc frame

while not window.closeRequested:
  pollEvents()
```
This leads to the following error:
```
Linking shaders failed:
: error: vertex shader output `color' declared as type `vec4', but fragment shader input declared as type `vec2'
```
This is on Fedora 35, X11 Linux, 8th gen Intel CPU (with integrated graphics). So not brand new, but not super old either. I'm hoping this issue is just me failing to install some obscure dependency rather than an actual bug in shady/boxy/windy, as I believe the examples do work on Windows?

Thanks for taking a look at this issue!

**Comment by treeform** [comment]
I have committed a change to the color shaders. If you pull HEAD can you see if that works for you now?

**Comment by ajusa** [comment]
Just pulled head and it works! Thank you for fixing it :)
