### ISSUE TITLE
How to control animation?

### ISSUE THREAD

**Issue by geohuz** [treeform/boxy#46]
I've played examples and I'm curious on animation control, for example how can I control the duration/speed, and how can I implement transition ease effect like linear, elastic, bounce in html/css?

**Comment by treeform** [comment]
With Boxy, you define the animation. You do it all yourself. Boxy is just for drawing. Draw stuff differently every frame to make animation. You could take epochTime() and use that for your animation as we do in examples, but there are many ways to do it.
