### ISSUE TITLE
Incorrect positioning of images for certain rects in drawImage

### ISSUE THREAD

**Issue by creikey** [treeform/boxy#48]
With this code:

```nim
import boxy, opengl, windy, pixie, vmath

let windowSize = ivec2(1280, 800)

let window = newWindow("Broken Image", windowSize)
makeContextCurrent(window)

loadExtensions()

let bxy = newBoxy()

let testImage = newImage(400, 400)
testImage.fill(rgba(255, 255, 255, 255))
newContext(testImage).strokeSegment(segment(vec2(0), vec2(400)))

bxy.addImage("test", testImage)

# Called when it is time to draw a new frame.
proc display() =

  bxy.beginFrame(windowSize)

  bxy.drawImage("test", rect = rect(vec2(100.0, 0.0), vec2(300, 300) ))
  bxy.drawImage("test", rect = rect(vec2(100.0, 0.0), vec2(268, 268) ))

  bxy.endFrame()
  window.swapBuffers()

while not window.closeRequested:
  display()
  pollEvents()

``` 
Boxy draws this:
![image](https://user-images.githubusercontent.com/28424206/185115738-7fa93d57-2630-4606-8af2-eed09a03848c.png)

Where each instance of test image, although drawn from the same point, are offset from each other. This seems to have something to do with the rect's scale, it only happens under certain rect sizes.

**Comment by guzba** [comment]
Interesting issue, thanks for reporting. Looks like we're doing something wrong here we should fix.

**Comment by treeform** [comment]
Thank you for the issue. Its a small issue with mip-maping selector. Fixed now.
