### ISSUE TITLE
Ubuntu Linux errors running examples

### ISSUE THREAD

**Issue by matkuki** [treeform/boxy#58]
Hi, my specs:

- Ubuntu 22.04 x64
- Nim 1.6.12 (installed via `choosenim`)

Compiling the examples `basic_sdl2`, `basic_windy`, `basic_glfw` and `heart` works without problems, but running them throws these errors:

- basic_sdl2:
`/home/matic/.nimble/pkgs2/boxy-0.4.1-3a1bdaa054fad0cf67286b0b18498f07d846f6ac/boxy/glsl/410/atlas.vert:`

- basic_glfw:
`/home/matic/.nimble/pkgs2/boxy-0.4.1-3a1bdaa054fad0cf67286b0b18498f07d846f6ac/boxy/glsl/410/atlas.vert:`

- basic_windy:
`Vertex shader compilation failed:
/home/matic/.nimble/pkgs2/boxy-0.4.1-3a1bdaa054fad0cf67286b0b18498f07d846f6ac/boxy/glsl/410/atlas.vert(1(10): 0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES`

- heart:
`Vertex shader compilation failed:
/home/matic/.nimble/pkgs2/boxy-0.4.1-3a1bdaa054fad0cf67286b0b18498f07d846f6ac/boxy/glsl/410/atlas.vert(1(10): 0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES`

Any ideas how to fix this?
Thanks

**Comment by treeform** [comment]
Sorry, Boxy does not support OpenGL 3.30, only OpenGL 4.1 and above. You can probably fix this by installing different drivers.

**Comment by matkuki** [comment]
Ahh, ok, thanks 👍
